//! Symbolic Reduced model wrapper.
//!
//! Provenance: the Rust fragments included from `generated/*.rs` are
//! generated by `sensor_fusion/src/reduced/formulation.py` through
//! `sensor_fusion/code_gen.py`. This module provides stable Rust function
//! boundaries around those generated fragments; regenerate the include files
//! from the Python source instead of hand-editing formulas.
//!
//! The generated model implements the augmented Reduced documented in
//! `docs/reduced.pdf`: 18 error states
//! `[dtheta_v, dv_n, dp_n, dbg, dba, dpsi_vb]` and 15 process-noise states
//! `[gyro, accel, gyro_bias_rw, accel_bias_rw, mount_rw]`.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(clippy::disallowed_names)]
#![allow(clippy::neg_multiply)]

use crate::reduced::{ImuDelta, NominalState};

/// Number of Reduced error-state components.
pub const ERROR_STATES: usize = 18;
/// Number of Reduced process-noise components.
pub const NOISE_STATES: usize = 15;
/// Standard gravity used by generated Reduced equations, in meters per second squared.
pub const GRAVITY_MSS: f32 = 9.80665;

include!("generated/error_transition_support_generated.rs");

/// Linearized scalar-observation terms emitted by the generated Reduced model.
#[derive(Clone, Copy, Debug)]
pub struct ScalarObservation {
    /// Observation Jacobian row.
    pub h: [f32; ERROR_STATES],
    /// Kalman gain column for this scalar observation.
    pub k: [f32; ERROR_STATES],
    /// Innovation variance.
    pub s: f32,
}

/// Applies the generated nominal-state prediction to the Reduced nominal state.
pub fn predict_nominal(nominal: &mut NominalState, imu: ImuDelta) {
    predict_nominal_with_gravity(nominal, imu, GRAVITY_MSS);
}

/// Applies the generated nominal-state prediction with a caller-supplied local gravity magnitude.
pub fn predict_nominal_with_gravity(nominal: &mut NominalState, imu: ImuDelta, gravity_mss: f32) {
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let vn = nominal.vn;
    let ve = nominal.ve;
    let vd = nominal.vd;
    let pn = nominal.pn;
    let pe = nominal.pe;
    let pd = nominal.pd;
    let bgx = nominal.bgx;
    let bgy = nominal.bgy;
    let bgz = nominal.bgz;
    let bax = nominal.bax;
    let bay = nominal.bay;
    let baz = nominal.baz;
    let qcs0 = nominal.qcs0;
    let qcs1 = nominal.qcs1;
    let qcs2 = nominal.qcs2;
    let qcs3 = nominal.qcs3;
    let dax = imu.dax;
    let day = imu.day;
    let daz = imu.daz;
    let dvx = imu.dvx;
    let dvy = imu.dvy;
    let dvz = imu.dvz;
    let dt = imu.dt;
    let g = gravity_mss;

    include!("generated/nominal_prediction_generated.rs");
}

/// Returns the generated error-state transition and noise-input matrices.
pub fn error_transition(
    nominal: &NominalState,
    imu: ImuDelta,
) -> (
    [[f32; ERROR_STATES]; ERROR_STATES],
    [[f32; NOISE_STATES]; ERROR_STATES],
) {
    error_transition_with_gravity(nominal, imu, GRAVITY_MSS)
}

/// Returns generated error-state transition/noise matrices with caller-supplied local gravity.
pub fn error_transition_with_gravity(
    nominal: &NominalState,
    imu: ImuDelta,
    gravity_mss: f32,
) -> (
    [[f32; ERROR_STATES]; ERROR_STATES],
    [[f32; NOISE_STATES]; ERROR_STATES],
) {
    let mut f = [[0.0; ERROR_STATES]; ERROR_STATES];
    let mut noise_input = [[0.0; NOISE_STATES]; ERROR_STATES];
    let F = &mut f;
    let G = &mut noise_input;

    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let vn = nominal.vn;
    let ve = nominal.ve;
    let vd = nominal.vd;
    let pn = nominal.pn;
    let pe = nominal.pe;
    let pd = nominal.pd;
    let bgx = nominal.bgx;
    let bgy = nominal.bgy;
    let bgz = nominal.bgz;
    let bax = nominal.bax;
    let bay = nominal.bay;
    let baz = nominal.baz;
    let qcs0 = nominal.qcs0;
    let qcs1 = nominal.qcs1;
    let qcs2 = nominal.qcs2;
    let qcs3 = nominal.qcs3;
    let dax = imu.dax;
    let day = imu.day;
    let daz = imu.daz;
    let dvx = imu.dvx;
    let dvy = imu.dvy;
    let dvz = imu.dvz;
    let dt = imu.dt;
    let g = gravity_mss;

    include!("generated/error_transition_generated.rs");
    include!("generated/error_noise_input_generated.rs");

    (f, noise_input)
}

/// Returns the generated first-order attitude reset Jacobian block.
pub fn attitude_reset_jacobian(dtheta: [f32; 3]) -> [[f32; 3]; 3] {
    let mut G_reset_theta = [[0.0; 3]; 3];
    let dtheta_x = dtheta[0];
    let dtheta_y = dtheta[1];
    let dtheta_z = dtheta[2];

    include!("generated/attitude_reset_jacobian_generated.rs");

    G_reset_theta
}

/// Builds the generated GNSS north-position scalar observation.
pub fn gps_pos_n_observation(
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_pos_n: f32,
) -> ScalarObservation {
    let P = p;
    let R_POS_N = r_pos_n;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;
    include!("generated/gps_pos_n_generated.rs");
    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated GNSS east-position scalar observation.
pub fn gps_pos_e_observation(
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_pos_e: f32,
) -> ScalarObservation {
    let P = p;
    let R_POS_E = r_pos_e;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;
    include!("generated/gps_pos_e_generated.rs");
    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated GNSS down-position scalar observation.
pub fn gps_pos_d_observation(
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_pos_d: f32,
) -> ScalarObservation {
    let P = p;
    let R_POS_D = r_pos_d;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;
    include!("generated/gps_pos_d_generated.rs");
    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated GNSS north-velocity scalar observation.
pub fn gps_vel_n_observation(
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_vel_n: f32,
) -> ScalarObservation {
    let P = p;
    let R_VEL_N = r_vel_n;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;
    include!("generated/gps_vel_n_generated.rs");
    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated GNSS east-velocity scalar observation.
pub fn gps_vel_e_observation(
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_vel_e: f32,
) -> ScalarObservation {
    let P = p;
    let R_VEL_E = r_vel_e;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;
    include!("generated/gps_vel_e_generated.rs");
    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated GNSS down-velocity scalar observation.
pub fn gps_vel_d_observation(
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_vel_d: f32,
) -> ScalarObservation {
    let P = p;
    let R_VEL_D = r_vel_d;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;
    include!("generated/gps_vel_d_generated.rs");
    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated stationary-gravity X-axis scalar observation.
pub fn stationary_accel_x_observation(
    nominal: &NominalState,
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_stationary_accel: f32,
) -> ScalarObservation {
    let P = p;
    let R_STATIONARY_ACCEL = r_stationary_accel;
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let bax = nominal.bax;
    let g = GRAVITY_MSS;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;

    include!("generated/stationary_accel_x_generated.rs");

    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated stationary-gravity Y-axis scalar observation.
pub fn stationary_accel_y_observation(
    nominal: &NominalState,
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_stationary_accel: f32,
) -> ScalarObservation {
    let P = p;
    let R_STATIONARY_ACCEL = r_stationary_accel;
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let bay = nominal.bay;
    let g = GRAVITY_MSS;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;

    include!("generated/stationary_accel_y_generated.rs");

    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated vehicle-frame forward-velocity scalar observation.
pub fn body_vel_x_observation(
    nominal: &NominalState,
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_body_vel: f32,
) -> ScalarObservation {
    let P = p;
    let R_BODY_VEL = r_body_vel;
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let qcs0 = nominal.qcs0;
    let qcs1 = nominal.qcs1;
    let qcs2 = nominal.qcs2;
    let qcs3 = nominal.qcs3;
    let vn = nominal.vn;
    let ve = nominal.ve;
    let vd = nominal.vd;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;

    include!("generated/body_vel_x_generated.rs");

    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated vehicle-frame lateral-velocity scalar observation.
pub fn body_vel_y_observation(
    nominal: &NominalState,
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_body_vel: f32,
) -> ScalarObservation {
    let P = p;
    let R_BODY_VEL = r_body_vel;
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let qcs0 = nominal.qcs0;
    let qcs1 = nominal.qcs1;
    let qcs2 = nominal.qcs2;
    let qcs3 = nominal.qcs3;
    let vn = nominal.vn;
    let ve = nominal.ve;
    let vd = nominal.vd;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;

    include!("generated/body_vel_y_generated.rs");

    ScalarObservation { h: H, k: K, s: S }
}

/// Builds the generated vehicle-frame vertical-velocity scalar observation.
pub fn body_vel_z_observation(
    nominal: &NominalState,
    p: &[[f32; ERROR_STATES]; ERROR_STATES],
    r_body_vel: f32,
) -> ScalarObservation {
    let P = p;
    let R_BODY_VEL = r_body_vel;
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let qcs0 = nominal.qcs0;
    let qcs1 = nominal.qcs1;
    let qcs2 = nominal.qcs2;
    let qcs3 = nominal.qcs3;
    let vn = nominal.vn;
    let ve = nominal.ve;
    let vd = nominal.vd;
    let mut H = [0.0; ERROR_STATES];
    let mut K = [0.0; ERROR_STATES];
    let mut S = 0.0;

    include!("generated/body_vel_z_generated.rs");

    ScalarObservation { h: H, k: K, s: S }
}
