//! Symbolic loose-filter model wrapper.
//!
//! Provenance: the Rust fragments included from `generated_loose/*.rs` are
//! generated by `ekf/ins_gnss_loose.py` through `ekf/code_gen.py`. This module
//! keeps the generated formulas behind small public functions; regenerate the
//! include files from the Python source instead of hand-editing formulas.
//!
//! The generated model follows `docs/loose_formulation.pdf`: 24 error states
//! `[dp_e, dv_e, dtheta_s, dba, dbg, dsa, dsg, dpsi_cs]` and 21 process-noise
//! states for accel/gyro white noise plus bias, scale, and mount random walks.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_assignments)]
#![allow(clippy::disallowed_names)]

use crate::loose::{LOOSE_ERROR_STATES, LOOSE_NOISE_STATES, LooseImuDelta, LooseNominalState};

include!("generated_loose/reference_support_generated.rs");

/// Returns the generated loose-filter error-state transition and noise-input matrices.
pub fn error_transition(
    nominal: &LooseNominalState,
    imu: LooseImuDelta,
) -> (
    [[f32; LOOSE_ERROR_STATES]; LOOSE_ERROR_STATES],
    [[f32; LOOSE_NOISE_STATES]; LOOSE_ERROR_STATES],
) {
    let mut f = [[0.0; LOOSE_ERROR_STATES]; LOOSE_ERROR_STATES];
    let mut noise_input = [[0.0; LOOSE_NOISE_STATES]; LOOSE_ERROR_STATES];
    let F = &mut f;
    let G = &mut noise_input;

    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let bax = nominal.bax;
    let bay = nominal.bay;
    let baz = nominal.baz;
    let sax = nominal.sax;
    let say = nominal.say;
    let saz = nominal.saz;
    let dax = imu.dax_2;
    let day = imu.day_2;
    let daz = imu.daz_2;
    let dvx = imu.dvx_2;
    let dvy = imu.dvy_2;
    let dvz = imu.dvz_2;
    let dt = imu.dt;

    include!("generated_loose/reference_error_noise_input_generated.rs");
    include!("generated_loose/reference_error_transition_generated.rs");

    (f, noise_input)
}

/// Returns the generated lateral nonholonomic-constraint estimate and Jacobian row.
pub fn nhc_y(nominal: &LooseNominalState) -> (f32, [f32; LOOSE_ERROR_STATES]) {
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let qcs0 = nominal.qcs0;
    let qcs1 = nominal.qcs1;
    let qcs2 = nominal.qcs2;
    let qcs3 = nominal.qcs3;
    let vn = nominal.vn;
    let ve = nominal.ve;
    let vd = nominal.vd;
    let mut vc_est = 0.0;
    let mut H = [0.0; LOOSE_ERROR_STATES];

    include!("generated_loose/reference_nhc_y_generated.rs");

    (vc_est, H)
}

/// Returns the generated vertical nonholonomic-constraint estimate and Jacobian row.
pub fn nhc_z(nominal: &LooseNominalState) -> (f32, [f32; LOOSE_ERROR_STATES]) {
    let q0 = nominal.q0;
    let q1 = nominal.q1;
    let q2 = nominal.q2;
    let q3 = nominal.q3;
    let qcs0 = nominal.qcs0;
    let qcs1 = nominal.qcs1;
    let qcs2 = nominal.qcs2;
    let qcs3 = nominal.qcs3;
    let vn = nominal.vn;
    let ve = nominal.ve;
    let vd = nominal.vd;
    let mut vc_est = 0.0;
    let mut H = [0.0; LOOSE_ERROR_STATES];

    include!("generated_loose/reference_nhc_z_generated.rs");

    (vc_est, H)
}
