{
// Generated by misalignment.py: gyro_rate_obs_jacobian_generated
let h_0: f32 = 1.0*yaw_rate_b*(q_sb0*q_sb0 - q_sb1*q_sb1 - q_sb2*q_sb2 + q_sb3*q_sb3);
let h_1: f32 = 2.0*yaw_rate_b;
let h_2: f32 = h_1*(q_sb0*q_sb1 - q_sb2*q_sb3);
let h_3: f32 = h_1*(q_sb0*q_sb2 + q_sb1*q_sb3);

H_gyro[0][0] = 0.0;
H_gyro[0][1] = h_0;
H_gyro[0][2] = h_2;
H_gyro[1][0] = -h_0;
H_gyro[1][1] = 0.0;
H_gyro[1][2] = h_3;
H_gyro[2][0] = -h_2;
H_gyro[2][1] = -h_3;
H_gyro[2][2] = 0.0;

}
