{
// Generated by misalignment.py: gyro_rate_pred_generated
let g_0: f32 = 2.0*yaw_rate_b;

gyro_pred[0] = g_0*(q_sb0*q_sb2 + q_sb1*q_sb3);
gyro_pred[1] = -g_0*(q_sb0*q_sb1 - q_sb2*q_sb3);
gyro_pred[2] = -yaw_rate_b*(2.0*q_sb1*q_sb1 + 2.0*q_sb2*q_sb2 - 1.0);

}
