{
// Generated by align.py: coarse_mekf_obs_generated
let c_0: f32 = q_vb0*q_vb3;
let c_1: f32 = q_vb1*q_vb2;
let c_2: f32 = c_0 + c_1;
let c_3: f32 = q_vb0*q_vb2;
let c_4: f32 = q_vb1*q_vb3;
let c_5: f32 = c_3 - c_4;
let c_6: f32 = 2.0*q_vb2*q_vb2;
let c_7: f32 = 2.0*q_vb3*q_vb3 - 1.0;
let c_8: f32 = c_6 + c_7;
let c_9: f32 = q_vb0*q_vb1;
let c_10: f32 = q_vb2*q_vb3;
let c_11: f32 = c_10 + c_9;
let c_12: f32 = c_0 - c_1;
let c_13: f32 = 2.0*q_vb1*q_vb1;
let c_14: f32 = c_13 + c_7;
let c_15: f32 = c_3 + c_4;
let c_16: f32 = -c_10 + c_9;
let c_17: f32 = c_13 + c_6 - 1.0;

coarse_obs[0] = 2.0*c_2*gyro_by - 2.0*c_5*gyro_bz - c_8*gyro_bx;
coarse_obs[1] = 2.0*c_11*gyro_bz - 2.0*c_12*gyro_bx - c_14*gyro_by;
coarse_obs[2] = 2.0*c_15*gyro_bx - 2.0*c_16*gyro_by - c_17*gyro_bz;
coarse_obs[3] = -accel_bx*c_8 + 2.0*accel_by*c_2 - 2.0*accel_bz*c_5;
coarse_obs[4] = -2.0*accel_bx*c_12 - accel_by*c_14 + 2.0*accel_bz*c_11;
coarse_obs[5] = 2.0*accel_bx*c_15 - 2.0*accel_by*c_16 - accel_bz*c_17;

}
