{
// Generated by align.py: coarse_mekf_obs_jacobian_generated
let j_0: f32 = q_vb0*q_vb3;
let j_1: f32 = q_vb1*q_vb2;
let j_2: f32 = j_0 + j_1;
let j_3: f32 = q_vb0*q_vb2;
let j_4: f32 = q_vb1*q_vb3;
let j_5: f32 = j_3 - j_4;
let j_6: f32 = 2.0*gyro_bx;
let j_7: f32 = q_vb1*q_vb1;
let j_8: f32 = q_vb2*q_vb2;
let j_9: f32 = -j_8;
let j_10: f32 = q_vb0*q_vb0;
let j_11: f32 = q_vb3*q_vb3;
let j_12: f32 = j_10 - j_11;
let j_13: f32 = j_12 + j_7 + j_9;
let j_14: f32 = 1.0*j_13;
let j_15: f32 = q_vb0*q_vb1;
let j_16: f32 = q_vb2*q_vb3;
let j_17: f32 = j_15 + j_16;
let j_18: f32 = 2.0*gyro_by;
let j_19: f32 = -j_7;
let j_20: f32 = j_12 + j_19 + j_8;
let j_21: f32 = j_0 - j_1;
let j_22: f32 = 1.0*j_20;
let j_23: f32 = j_15 - j_16;
let j_24: f32 = 2.0*gyro_bz;
let j_25: f32 = 1.0*j_10 + 1.0*j_11 + 1.0*j_19 + 1.0*j_9;
let j_26: f32 = j_3 + j_4;
let j_27: f32 = 2.0*accel_bx;
let j_28: f32 = 2.0*accel_by;
let j_29: f32 = 2.0*accel_bz;

H_coarse[0][0] = 2.0*gyro_by*j_5 + 2.0*gyro_bz*j_2;
H_coarse[0][1] = -gyro_bz*j_14 - j_5*j_6;
H_coarse[0][2] = 1.0*gyro_by*j_13 - j_2*j_6;
H_coarse[1][0] = 1.0*gyro_bz*j_20 - j_17*j_18;
H_coarse[1][1] = 2.0*gyro_bx*j_17 + 2.0*gyro_bz*j_21;
H_coarse[1][2] = -gyro_bx*j_22 - j_18*j_21;
H_coarse[2][0] = -gyro_by*j_25 - j_23*j_24;
H_coarse[2][1] = gyro_bx*j_25 - j_24*j_26;
H_coarse[2][2] = 2.0*gyro_bx*j_23 + 2.0*gyro_by*j_26;
H_coarse[3][0] = 2.0*accel_by*j_5 + 2.0*accel_bz*j_2;
H_coarse[3][1] = -accel_bz*j_14 - j_27*j_5;
H_coarse[3][2] = 1.0*accel_by*j_13 - j_2*j_27;
H_coarse[4][0] = 1.0*accel_bz*j_20 - j_17*j_28;
H_coarse[4][1] = 2.0*accel_bx*j_17 + 2.0*accel_bz*j_21;
H_coarse[4][2] = -accel_bx*j_22 - j_21*j_28;
H_coarse[5][0] = -accel_by*j_25 - j_23*j_29;
H_coarse[5][1] = accel_bx*j_25 - j_26*j_29;
H_coarse[5][2] = 2.0*accel_bx*j_23 + 2.0*accel_by*j_26;

}
