// Generated by align.py: predict_velocity_generated
let s_0: f32 = q_nb0*q_nb2;
let s_1: f32 = q_nb1*q_nb3;
let s_2: f32 = q_sb0*q_sb2;
let s_3: f32 = q_sb1*q_sb3;
let s_4: f32 = q_sb0*q_sb1;
let s_5: f32 = q_sb2*q_sb3;
let s_6: f32 = 2*q_sb1*q_sb1;
let s_7: f32 = 2*q_sb2*q_sb2 - 1;
let s_8: f32 = -2*f_sx*(s_2 + s_3) + 2*f_sy*(s_4 - s_5) + f_sz*(s_6 + s_7);
let s_9: f32 = -2*s_8;
let s_10: f32 = q_nb0*q_nb3;
let s_11: f32 = q_nb1*q_nb2;
let s_12: f32 = q_sb0*q_sb3;
let s_13: f32 = q_sb1*q_sb2;
let s_14: f32 = 2*q_sb3*q_sb3;
let s_15: f32 = 2*f_sx*(s_12 - s_13) + f_sy*(s_14 + s_6 - 1) - 2*f_sz*(s_4 + s_5);
let s_16: f32 = -s_15;
let s_17: f32 = 2*q_nb2*q_nb2;
let s_18: f32 = 2*q_nb3*q_nb3 - 1;
let s_19: f32 = f_sx*(s_14 + s_7) - 2*f_sy*(s_12 + s_13) + 2*f_sz*(s_2 - s_3);
let s_20: f32 = -s_19;
let s_21: f32 = q_nb0*q_nb1;
let s_22: f32 = q_nb2*q_nb3;
let s_23: f32 = 2*q_nb1*q_nb1;

v_pred_n[0] = -dt*(2*s_16*(s_10 - s_11) + s_20*(s_17 + s_18) - s_9*(s_0 + s_1)) + v_anchor_n;
v_pred_n[1] = -dt*(s_16*(s_18 + s_23) - 2*s_20*(s_10 + s_11) + s_9*(s_21 - s_22)) + v_anchor_e;
v_pred_n[2] = dt*(g - 2*s_15*(s_21 + s_22) + 2*s_19*(s_0 - s_1) + s_8*(s_17 + s_23 - 1)) + v_anchor_d;

