import os

from sympy import Matrix, cse, symbols

from code_gen import CodeGenerator


def quat2rot(q):
    q0, q1, q2, q3 = q
    return Matrix(
        [
            [
                1 - 2 * q2**2 - 2 * q3**2,
                2 * (q1 * q2 - q0 * q3),
                2 * (q1 * q3 + q0 * q2),
            ],
            [
                2 * (q1 * q2 + q0 * q3),
                1 - 2 * q1**2 - 2 * q3**2,
                2 * (q2 * q3 - q0 * q1),
            ],
            [
                2 * (q1 * q3 - q0 * q2),
                2 * (q2 * q3 + q0 * q1),
                1 - 2 * q1**2 - 2 * q2**2,
            ],
        ]
    )


def quat_mult(p, q):
    return Matrix(
        [
            p[0] * q[0] - p[1] * q[1] - p[2] * q[2] - p[3] * q[3],
            p[0] * q[1] + p[1] * q[0] + p[2] * q[3] - p[3] * q[2],
            p[0] * q[2] - p[1] * q[3] + p[2] * q[0] + p[3] * q[1],
            p[0] * q[3] + p[1] * q[2] - p[2] * q[1] + p[3] * q[0],
        ]
    )


def write_pair(file_stem, subs, output, output_name, is_matrix):
    c_file = CodeGenerator(f"./c/generated/{file_stem}.c", "c")
    c_file.print_string(f"Generated by align.py: {file_stem}")
    c_file.write_subexpressions(subs)
    if is_matrix:
        c_file.write_matrix(output, output_name)
    else:
        c_file.write_vector(output, output_name)
    c_file.close()

    rs_file = CodeGenerator(f"./src/align_generated/{file_stem}.rs", "rust")
    rs_file.file.write("{\n")
    rs_file.print_string(f"Generated by align.py: {file_stem}")
    rs_file.write_subexpressions(subs)
    if is_matrix:
        rs_file.write_matrix(output, output_name)
    else:
        rs_file.write_vector(output, output_name)
    rs_file.file.write("}\n")
    rs_file.close()


def generate_code():
    if not os.path.exists("c/generated"):
        os.makedirs("c/generated")
    if not os.path.exists("src/align_generated"):
        os.makedirs("src/align_generated")

    # Installation quaternion q_sb maps body->sensor.
    q0, q1, q2, q3 = symbols("q_sb0 q_sb1 q_sb2 q_sb3", real=True)
    q_sb = Matrix([q0, q1, q2, q3])

    # Small-angle perturbation in body frame.
    dtx, dty, dtz = symbols("dtx dty dtz", real=True)
    dq = Matrix([1, 0.5 * dtx, 0.5 * dty, 0.5 * dtz])
    q_sb_plus = quat_mult(dq, q_sb)

    # Body yaw-rate proxy from GNSS course rate.
    yaw_rate_b = symbols("yaw_rate_b", real=True)
    omega_b = Matrix([0, 0, yaw_rate_b])

    # Predicted sensor angular rate and jacobian wrt small-angle perturbation.
    omega_s_pred = quat2rot(q_sb) * omega_b
    omega_s_pred_plus = quat2rot(q_sb_plus) * omega_b
    H_gyro = omega_s_pred_plus.jacobian(Matrix([dtx, dty, dtz])).subs(
        {dtx: 0, dty: 0, dtz: 0}
    )

    pred_simple = cse(omega_s_pred, symbols("g_0:200"), optimizations="basic")
    write_pair(
        "gyro_rate_pred_generated",
        pred_simple[0],
        pred_simple[1][0],
        "gyro_pred",
        is_matrix=False,
    )

    jac_simple = cse(H_gyro, symbols("h_0:400"), optimizations="basic")
    write_pair(
        "gyro_rate_obs_jacobian_generated",
        jac_simple[0],
        jac_simple[1][0],
        "H_gyro",
        is_matrix=True,
    )

    # Coarse mount MEKF observation model: vehicle-frame gyro and accel from q_vb.
    qv0, qv1, qv2, qv3 = symbols("q_vb0 q_vb1 q_vb2 q_vb3", real=True)
    q_vb = Matrix([qv0, qv1, qv2, qv3])
    dq = Matrix([1, 0.5 * dtx, 0.5 * dty, 0.5 * dtz])
    q_vb_plus = quat_mult(dq, q_vb)

    gyro_bx, gyro_by, gyro_bz = symbols("gyro_bx gyro_by gyro_bz", real=True)
    accel_bx, accel_by, accel_bz = symbols("accel_bx accel_by accel_bz", real=True)
    gyro_b = Matrix([gyro_bx, gyro_by, gyro_bz])
    accel_b = Matrix([accel_bx, accel_by, accel_bz])

    C_bv = quat2rot(q_vb).T
    C_bv_plus = quat2rot(q_vb_plus).T
    coarse_obs = Matrix.vstack(C_bv * gyro_b, C_bv * accel_b)
    coarse_obs_plus = Matrix.vstack(C_bv_plus * gyro_b, C_bv_plus * accel_b)
    H_coarse = coarse_obs_plus.jacobian(Matrix([dtx, dty, dtz])).subs(
        {dtx: 0, dty: 0, dtz: 0}
    )

    coarse_simple = cse(coarse_obs, symbols("c_0:400"), optimizations="basic")
    write_pair(
        "coarse_mekf_obs_generated",
        coarse_simple[0],
        coarse_simple[1][0],
        "coarse_obs",
        is_matrix=False,
    )

    coarse_jac = cse(H_coarse, symbols("j_0:600"), optimizations="basic")
    write_pair(
        "coarse_mekf_obs_jacobian_generated",
        coarse_jac[0],
        coarse_jac[1][0],
        "H_coarse",
        is_matrix=True,
    )

    print("Align symbolic code generation complete.")


if __name__ == "__main__":
    generate_code()
